name: Mirror Repository

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora
  workflow_dispatch:
env:
  ORG_NAME: dragonstone-org
  REPO_URL: https://github.com/dragonstone-org/mirrored-tour-of-heroes-dotnet-api.git

jobs: 
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Generate token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.DRAGONSTONE_APP_ID }}
        private-key: ${{ secrets.DRAGONSTONE_PRIVATE_KEY }}
        owner: ${{ env.ORG_NAME }}

    - name: List the repos that I can see
      run: |
        gh api "/orgs/$ORG_NAME/repos"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        
    - name: Get GitHub App User ID
      id: get-user-id
      run: |  
        user_id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)
        echo "The user id is: $user_id"
        echo "user-id=$user_id" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }} [bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
      # git commands like commit work using the bot user   

    - name: Push to mirror repository
      run: |
        git push --mirror ${{ env.REPO_URL }}
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
