name: Mirror Repository

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora
  workflow_dispatch:

jobs: 
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: returngis/tour-of-heroes-api-dotnet-9
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.DRAGONSTONE_APP_ID }}
        private-key: ${{ secrets.DRAGONSTONE_PRIVATE_KEY }}
        owner: dragonstone-org
    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
      # git commands like commit work using the bot user   

    - name: Push to mirror repository
      run: |
        git push --mirror https://github.com/dragonstone-org/mirrored-repo.git
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
